name: Capstone Wealth Partners
favicon: null
layout_spectrum: 0.33529266249388456
typography_spectrum: 0.7453080934938043
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9657368848565966
  lightness: 0.9694330124184489
  saturation: 0.5062568674329668
  rhythmicContrast: 0.08807753026485443
purpose: []
