name: Capstone Wealth Partners
favicon: null
layout_spectrum: 0.62098
typography_spectrum: 0.56772
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#dc7a2c'
    - '#1384a7'
    - '#a3a526'
    - '#717173'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
